import { Controller, Get } from '@nestjs/common';
import { ApiOperation, ApiTags } from '@nestjs/swagger';

/**
 * AI API Documentation Generator — roadmap (MD44); IA opcional; privacy-first.
 */
@ApiTags('ai-docs')
@Controller('api/ai-docs')
export class AiDocsRoadmapController {
  @Get('roadmap')
  @ApiOperation({
    summary:
      'Gerar documentação de APIs/coleções com IA — stub MD44 (providers futuros)',
  })
  roadmap(): {
    phase: string;
    md: string;
    description: string;
    principles: readonly string[];
    strategicGoals: readonly string[];
    primaryFlowSteps: readonly string[];
    generatedDocSections: readonly string[];
    restExamplePath: string;
    providersFuture: readonly string[];
    exportsFuture: readonly string[];
    integrations: readonly string[];
    openApiIntegrationFuture: readonly string[];
    futureFeatures: readonly string[];
    uxRequirements: readonly string[];
    safetyRules: readonly string[];
    deferred: readonly string[];
    futureThemes: readonly string[];
    plannedUiComponents: readonly string[];
    mvpGoals: readonly string[];
    frontendStructure: string;
    backendLayout: {
      moduleRoot: string;
      providers: string;
      prompts: string;
      generators: string;
    };
  } {
    return {
      phase: 'roadmap',
      md: 'MD44_JUNNY_AI_API_DOCUMENTATION_GENERATOR.md',
      description:
        'Roadmap para gerar documentação markdown/HTML a partir de requests, coleções e OpenAPI (descrições em falta, exemplos), com fluxo Generate Docs, preview e export — IA sempre opcional, controlos de privacidade (payloads, providers, modo local) e regras que impedem envio automático de secrets/tokens/passwords.',
      principles: ['ia-opcional', 'privacy-first', 'nucleo-util-sem-ia'],
      strategicGoals: [
        'plataforma inteligente para documentação e explainability de APIs',
        'reduzir documentação manual, onboarding lento e APIs opacas',
        'aumentar produtividade real com opt-in claro a providers externos',
      ],
      primaryFlowSteps: [
        'selecionar request ou collection',
        'clicar Generate Docs',
        'IA (ou motor local futuro) gera documentação editável',
      ],
      generatedDocSections: [
        'endpoint description',
        'auth explanation',
        'examples',
        'payload explanation',
        'response explanation',
      ],
      restExamplePath: 'GET /users',
      providersFuture: ['OpenAI', 'OpenRouter', 'Ollama', 'Anthropic', 'modelos locais'],
      exportsFuture: ['markdown export', 'HTML export', 'docs portal integration'],
      integrations: ['Collection → Generate Documentation'],
      openApiIntegrationFuture: ['enrich OpenAPI', 'missing descriptions', 'examples generation'],
      futureFeatures: [
        'onboarding guides',
        'architecture explanations',
        'API tutorials',
        'autogenerated examples',
      ],
      uxRequirements: ['extremamente simples', 'impressionante', 'útil', 'moderna', 'dark-first'],
      safetyRules: [
        'nunca enviar automaticamente secrets, passwords ou tokens aos providers',
      ],
      deferred: [
        'publicação autónoma de docs',
        'IA cloud obrigatória',
        'telemetria sobre conteúdo gerado',
        'auto publish sem revisão',
      ],
      futureThemes: [
        'multilingual docs',
        'AI tutorials',
        'architecture diagrams',
        'onboarding assistant',
      ],
      plannedUiComponents: [
        'GenerateDocsButton',
        'DocsPreview',
        'MarkdownViewer',
        'ExampleGenerator',
      ],
      mvpGoals: [
        'generate endpoint docs',
        'generate examples',
        'markdown generation',
        'collection documentation',
      ],
      frontendStructure: '/features/ai-docs',
      backendLayout: {
        moduleRoot: '/modules/ai-docs',
        providers: '/modules/ai-docs/providers',
        prompts: '/modules/ai-docs/prompts',
        generators: '/modules/ai-docs/generators',
      },
    };
  }
}
